# Source of truth for UI strings: key -> (English, Kannada, Hindi).
# Run `python3 tool/gen_arb.py` to regenerate lib/core/l10n/app_*.arb.
# Placeholders use {name}; int placeholders are listed in INT_PARAMS.
S = {
 "appName": ("Beat Mitra", "ಬೀಟ್ ಮಿತ್ರ", "बीट मित्र"),
 "appTagline": ("Your helper for the delivery beat", "ನಿಮ್ಮ ಬೀಟ್ ಸಹಾಯಕ", "आपकी बीट का साथी"),
 "welcomeTitle": ("Welcome", "ಸ್ವಾಗತ", "स्वागत है"),
 "chooseLanguage": ("Choose language", "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ", "भाषा चुनें"),
 "next": ("Next", "ಮುಂದೆ", "आगे"),
 "iUnderstand": ("I understand", "ನನಗೆ ಅರ್ಥವಾಯಿತು", "मैं समझ गया"),
 "disclaimer": ("Independent helper tool for postmen. Not an official Department of Posts app. Follow your office's rules on customer information.",
   "ಅಂಚೆಯಣ್ಣರಿಗಾಗಿ ಸ್ವತಂತ್ರ ಸಹಾಯಕ ಸಾಧನ. ಇದು ಅಂಚೆ ಇಲಾಖೆಯ ಅಧಿಕೃತ ಆ್ಯಪ್ ಅಲ್ಲ. ಗ್ರಾಹಕರ ಮಾಹಿತಿಯ ಬಗ್ಗೆ ನಿಮ್ಮ ಕಚೇರಿಯ ನಿಯಮಗಳನ್ನು ಪಾಲಿಸಿ.",
   "डाकियों के लिए स्वतंत्र सहायक टूल। यह डाक विभाग का आधिकारिक ऐप नहीं है। ग्राहकों की जानकारी के बारे में अपने कार्यालय के नियमों का पालन करें।"),
 "privacyTitle": ("Privacy", "ಗೌಪ್ಯತೆ", "गोपनीयता"),
 "privacyOnDevice": ("Names and addresses stay only on this phone.", "ಹೆಸರು ಮತ್ತು ವಿಳಾಸಗಳು ಈ ಫೋನಿನಲ್ಲಿ ಮಾತ್ರ ಇರುತ್ತವೆ.", "नाम और पते केवल इसी फ़ोन में रहते हैं।"),
 "privacyEncrypted": ("All data and photos are encrypted and protected by your PIN.", "ಎಲ್ಲಾ ಮಾಹಿತಿ ಮತ್ತು ಫೋಟೋಗಳು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಆಗಿವೆ, ನಿಮ್ಮ PIN ನಿಂದ ರಕ್ಷಿತ.", "सारा डेटा और फ़ोटो एन्क्रिप्टेड हैं और आपके PIN से सुरक्षित हैं।"),
 "privacyNoCloud": ("No internet, no cloud, no login, no ads.", "ಇಂಟರ್ನೆಟ್ ಇಲ್ಲ, ಕ್ಲೌಡ್ ಇಲ್ಲ, ಲಾಗಿನ್ ಇಲ್ಲ, ಜಾಹೀರಾತು ಇಲ್ಲ.", "न इंटरनेट, न क्लाउड, न लॉगिन, न विज्ञापन।"),
 "privacyNoAnalytics": ("No analytics or crash reporting.", "ಯಾವುದೇ ಅನಾಲಿಟಿಕ್ಸ್ ಅಥವಾ ಕ್ರ್ಯಾಶ್ ವರದಿ ಇಲ್ಲ.", "कोई एनालिटिक्स या क्रैश रिपोर्टिंग नहीं।"),
 "privacyMap": ("The optional online map is OFF by default and only loads map pictures from OpenStreetMap.", "ಆಯ್ಕೆಯ ಆನ್‌ಲೈನ್ ನಕ್ಷೆ ಮೊದಲಿಗೆ ಆಫ್ ಆಗಿರುತ್ತದೆ; ಅದು OpenStreetMap ನಿಂದ ನಕ್ಷೆಯ ಚಿತ್ರಗಳನ್ನು ಮಾತ್ರ ತರುತ್ತದೆ.", "वैकल्पिक ऑनलाइन नक्शा शुरू में बंद रहता है और केवल OpenStreetMap से नक्शे की तस्वीरें लाता है।"),
 "privacyBackupAdvice": ("Data is only on this phone: make an encrypted backup every week.", "ಮಾಹಿತಿ ಈ ಫೋನಿನಲ್ಲಿ ಮಾತ್ರ ಇದೆ: ಪ್ರತಿ ವಾರ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಬ್ಯಾಕಪ್ ಮಾಡಿ.", "डेटा केवल इसी फ़ोन में है: हर हफ़्ते एन्क्रिप्टेड बैकअप बनाएँ।"),
 "freeTools": ("Built only with free and open tools. Works fully offline.", "ಉಚಿತ ಮತ್ತು ಮುಕ್ತ ಸಾಧನಗಳಿಂದ ಮಾತ್ರ ನಿರ್ಮಿತ. ಸಂಪೂರ್ಣ ಆಫ್‌ಲೈನ್‌ನಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ.", "केवल मुफ़्त और ओपन टूल से बना। पूरी तरह ऑफ़लाइन चलता है।"),
 "createPin": ("Create a 4-digit PIN", "4 ಅಂಕಿಯ PIN ರಚಿಸಿ", "4 अंकों का PIN बनाएँ"),
 "confirmPin": ("Enter the PIN again", "PIN ಅನ್ನು ಮತ್ತೊಮ್ಮೆ ನಮೂದಿಸಿ", "PIN फिर से डालें"),
 "pinMismatch": ("PINs did not match. Try again.", "PIN ಹೊಂದಿಕೆಯಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.", "PIN मेल नहीं खाए। फिर कोशिश करें।"),
 "enterPin": ("Enter PIN", "PIN ನಮೂದಿಸಿ", "PIN डालें"),
 "enterOldPin": ("Enter current PIN", "ಈಗಿನ PIN ನಮೂದಿಸಿ", "मौजूदा PIN डालें"),
 "wrongPin": ("Wrong PIN", "ತಪ್ಪು PIN", "गलत PIN"),
 "tooManyTries": ("Too many tries. Wait 30 seconds.", "ಹಲವು ಬಾರಿ ತಪ್ಪಾಗಿದೆ. 30 ಸೆಕೆಂಡ್ ಕಾಯಿರಿ.", "बहुत बार गलत। 30 सेकंड रुकें।"),
 "useFingerprint": ("Unlock with fingerprint / face", "ಬೆರಳಚ್ಚು / ಮುಖದಿಂದ ತೆರೆಯಿರಿ", "फ़िंगरप्रिंट / चेहरे से खोलें"),
 "unlockReason": ("Unlock Beat Mitra", "ಬೀಟ್ ಮಿತ್ರ ತೆರೆಯಿರಿ", "बीट मित्र खोलें"),
 "biometricUnavailable": ("Not available on this phone", "ಈ ಫೋನಿನಲ್ಲಿ ಲಭ್ಯವಿಲ್ಲ", "इस फ़ोन पर उपलब्ध नहीं"),
 "pinChanged": ("PIN changed", "PIN ಬದಲಾಯಿತು", "PIN बदल गया"),
 "ok": ("OK", "ಸರಿ", "ठीक है"),
 "cancel": ("Cancel", "ರದ್ದು", "रद्द करें"),
 "save": ("Save", "ಉಳಿಸಿ", "सहेजें"),
 "saved": ("Saved", "ಉಳಿಸಲಾಗಿದೆ", "सहेजा गया"),
 "delete": ("Delete", "ಅಳಿಸಿ", "हटाएँ"),
 "edit": ("Edit", "ತಿದ್ದು", "बदलें"),
 "add": ("Add", "ಸೇರಿಸಿ", "जोड़ें"),
 "remove": ("Remove", "ತೆಗೆದುಹಾಕಿ", "हटाएँ"),
 "done": ("Done", "ಮುಗಿಯಿತು", "हो गया"),
 "clear": ("Clear", "ಅಳಿಸು", "साफ़ करें"),
 "select": ("Select", "ಆಯ್ಕೆಮಾಡಿ", "चुनें"),
 "share": ("Share", "ಹಂಚಿಕೊಳ್ಳಿ", "शेयर करें"),
 "title": ("Title", "ಶೀರ್ಷಿಕೆ", "शीर्षक"),
 "note": ("Note", "ಟಿಪ್ಪಣಿ", "नोट"),
 "notes": ("Notes", "ಟಿಪ್ಪಣಿಗಳು", "नोट्स"),
 "noteOptional": ("Note (optional)", "ಟಿಪ್ಪಣಿ (ಐಚ್ಛಿಕ)", "नोट (वैकल्पिक)"),
 "settings": ("Settings", "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", "सेटिंग्स"),
 "help": ("Help", "ಸಹಾಯ", "मदद"),
 "about": ("About", "ಬಗ್ಗೆ", "जानकारी"),
 "voiceInput": ("Speak", "ಮಾತನಾಡಿ", "बोलें"),
 "voiceStop": ("Stop listening", "ಆಲಿಸುವುದನ್ನು ನಿಲ್ಲಿಸಿ", "सुनना बंद करें"),
 "voiceNotHeard": ("Could not hear. Try again or type.", "ಕೇಳಿಸಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಟೈಪ್ ಮಾಡಿ.", "सुनाई नहीं दिया। फिर कोशिश करें या टाइप करें।"),
 "somethingWrong": ("Something went wrong", "ಏನೋ ತಪ್ಪಾಗಿದೆ", "कुछ गड़बड़ हुई"),
 "switchBeat": ("Switch beat", "ಬೀಟ್ ಬದಲಿಸಿ", "बीट बदलें"),
 "noBeatYet": ("No beat yet. Create your beat to start.", "ಇನ್ನೂ ಬೀಟ್ ಇಲ್ಲ. ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಬೀಟ್ ರಚಿಸಿ.", "अभी कोई बीट नहीं। शुरू करने के लिए अपनी बीट बनाएँ।"),
 "createBeat": ("Create beat", "ಬೀಟ್ ರಚಿಸಿ", "बीट बनाएँ"),
 "editBeat": ("Edit beat", "ಬೀಟ್ ತಿದ್ದು", "बीट बदलें"),
 "deleteBeat": ("Delete beat", "ಬೀಟ್ ಅಳಿಸಿ", "बीट हटाएँ"),
 "deleteBeatConfirm": ("Delete this beat with its {count} places, streets and photos?", "ಈ ಬೀಟ್ ಮತ್ತು ಅದರ {count} ಸ್ಥಳಗಳು, ರಸ್ತೆಗಳು, ಫೋಟೋಗಳನ್ನು ಅಳಿಸುವುದೇ?", "इस बीट को इसकी {count} जगहों, गलियों और फ़ोटो के साथ हटाएँ?"),
 "beats": ("Beats", "ಬೀಟ್‌ಗಳು", "बीट"),
 "beatName": ("Beat name", "ಬೀಟ್ ಹೆಸರು", "बीट का नाम"),
 "beatNameHint": ("e.g. Beat 7 / Relief beat 3", "ಉದಾ. ಬೀಟ್ 7 / ರಿಲೀಫ್ ಬೀಟ್ 3", "जैसे बीट 7 / रिलीफ़ बीट 3"),
 "office": ("Post office", "ಅಂಚೆ ಕಚೇರಿ", "डाकघर"),
 "addHere": ("Add here", "ಇಲ್ಲಿ ಸೇರಿಸಿ", "यहाँ जोड़ें"),
 "searchHint": ("Name, door no., street, landmark, PIN…", "ಹೆಸರು, ಮನೆ ಸಂಖ್ಯೆ, ರಸ್ತೆ, ಗುರುತು, PIN…", "नाम, मकान नं., गली, निशानी, PIN…"),
 "search": ("Search", "ಹುಡುಕಿ", "खोजें"),
 "todaysArticles": ("Today's articles", "ಇಂದಿನ ಟಪಾಲುಗಳು", "आज की डाक"),
 "pendingDoneCount": ("{pending} to deliver · {done} done", "{pending} ತಲುಪಿಸಬೇಕು · {done} ಮುಗಿದಿದೆ", "{pending} बाँटनी हैं · {done} हो गईं"),
 "routeAndRun": ("Route & delivery", "ಮಾರ್ಗ ಮತ್ತು ವಿತರಣೆ", "रास्ता और वितरण"),
 "nearby": ("Nearby places", "ಹತ್ತಿರದ ಸ್ಥಳಗಳು", "आस-पास की जगहें"),
 "daySummary": ("Day summary", "ದಿನದ ಸಾರಾಂಶ", "दिन का सारांश"),
 "beatAndStreets": ("Beat & streets", "ಬೀಟ್ ಮತ್ತು ರಸ್ತೆಗಳು", "बीट और गलियाँ"),
 "learnBeat": ("Learn the beat", "ಬೀಟ್ ಕಲಿಯಿರಿ", "बीट सीखें"),
 "handoverBackup": ("Handover & backup", "ಹಸ್ತಾಂತರ ಮತ್ತು ಬ್ಯಾಕಪ್", "सौंपना और बैकअप"),
 "map": ("Map", "ನಕ್ಷೆ", "नक्शा"),
 "backupReminder": ("No backup in the last 7 days. Your data is only on this phone — back up now.", "ಕಳೆದ 7 ದಿನಗಳಲ್ಲಿ ಬ್ಯಾಕಪ್ ಇಲ್ಲ. ಮಾಹಿತಿ ಈ ಫೋನಿನಲ್ಲಿ ಮಾತ್ರ ಇದೆ — ಈಗಲೇ ಬ್ಯಾಕಪ್ ಮಾಡಿ.", "पिछले 7 दिनों में बैकअप नहीं। डेटा केवल इसी फ़ोन में है — अभी बैकअप लें।"),
 "streets": ("Streets", "ರಸ್ತೆಗಳು", "गलियाँ"),
 "streetsHelp": ("Drag ≡ to put streets in your usual walking order.", "ನಿಮ್ಮ ಸಾಮಾನ್ಯ ನಡಿಗೆಯ ಕ್ರಮಕ್ಕೆ ರಸ್ತೆಗಳನ್ನು ≡ ಎಳೆದು ಜೋಡಿಸಿ.", "गलियों को अपने रोज़ के चलने के क्रम में लगाने के लिए ≡ खींचें।"),
 "noStreets": ("No streets yet. Add the streets of your beat.", "ಇನ್ನೂ ರಸ್ತೆಗಳಿಲ್ಲ. ನಿಮ್ಮ ಬೀಟ್‌ನ ರಸ್ತೆಗಳನ್ನು ಸೇರಿಸಿ.", "अभी कोई गली नहीं। अपनी बीट की गलियाँ जोड़ें।"),
 "addStreet": ("Add street", "ರಸ್ತೆ ಸೇರಿಸಿ", "गली जोड़ें"),
 "editStreet": ("Edit street", "ರಸ್ತೆ ತಿದ್ದು", "गली बदलें"),
 "deleteStreet": ("Delete street", "ರಸ್ತೆ ಅಳಿಸಿ", "गली हटाएँ"),
 "deleteStreetConfirm": ("Delete this street? Its places stay, without a street.", "ಈ ರಸ್ತೆ ಅಳಿಸುವುದೇ? ಅದರ ಸ್ಥಳಗಳು ರಸ್ತೆಯಿಲ್ಲದೆ ಉಳಿಯುತ್ತವೆ.", "यह गली हटाएँ? इसकी जगहें बिना गली के बनी रहेंगी।"),
 "streetName": ("Street name", "ರಸ್ತೆಯ ಹೆಸರು", "गली का नाम"),
 "streetNameHint": ("e.g. 4th Cross, 2nd Main, HAL 2nd Stage", "ಉದಾ. 4ನೇ ಕ್ರಾಸ್, 2ನೇ ಮೇನ್, HAL 2ನೇ ಹಂತ", "जैसे 4th क्रॉस, गली नं. 3, शास्त्री नगर"),
 "area": ("Area", "ಪ್ರದೇಶ", "इलाका"),
 "crossMainNote": ("Cross / main note", "ಕ್ರಾಸ್ / ಮೇನ್ ಟಿಪ್ಪಣಿ", "क्रॉस / मेन नोट"),
 "placesCount": ("Places: {count}", "ಸ್ಥಳಗಳು: {count}", "जगहें: {count}"),
 "noPlaces": ("No places yet. Walk your beat and tap “Add here” at each door.", "ಇನ್ನೂ ಸ್ಥಳಗಳಿಲ್ಲ. ಬೀಟ್‌ನಲ್ಲಿ ನಡೆಯುತ್ತಾ ಪ್ರತಿ ಮನೆಯ ಬಳಿ “ಇಲ್ಲಿ ಸೇರಿಸಿ” ಒತ್ತಿ.", "अभी कोई जगह नहीं। बीट पर चलते हुए हर दरवाज़े पर “यहाँ जोड़ें” दबाएँ।"),
 "noStreet": ("No street", "ರಸ್ತೆ ಇಲ್ಲ", "बिना गली"),
 "areaNotes": ("Area notes", "ಪ್ರದೇಶದ ಟಿಪ್ಪಣಿ", "इलाके के नोट"),
 "areaNote": ("Area note", "ಪ್ರದೇಶದ ಟಿಪ್ಪಣಿ", "इलाके का नोट"),
 "areaNoteHint": ("e.g. cross numbers increase towards the lake", "ಉದಾ. ಕೆರೆಯ ಕಡೆಗೆ ಕ್ರಾಸ್ ಸಂಖ್ಯೆ ಹೆಚ್ಚಾಗುತ್ತದೆ", "जैसे झील की ओर क्रॉस नंबर बढ़ते हैं"),
 "addAreaNote": ("Add area note", "ಪ್ರದೇಶದ ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ", "इलाके का नोट जोड़ें"),
 "noAreaNotes": ("Write how numbering works here, short cuts, timings…", "ಇಲ್ಲಿ ಸಂಖ್ಯೆ ಹೇಗಿದೆ, ಒಳದಾರಿ, ಸಮಯ… ಬರೆಯಿರಿ", "यहाँ नंबर कैसे चलते हैं, छोटे रास्ते, समय… लिखें"),
 "addPlace": ("Add place", "ಸ್ಥಳ ಸೇರಿಸಿ", "जगह जोड़ें"),
 "editPlace": ("Edit place", "ಸ್ಥಳ ತಿದ್ದು", "जगह बदलें"),
 "deletePlace": ("Delete place", "ಸ್ಥಳ ಅಳಿಸಿ", "जगह हटाएँ"),
 "deletePlaceConfirm": ("Delete this place, its names and photos?", "ಈ ಸ್ಥಳ, ಅದರ ಹೆಸರುಗಳು ಮತ್ತು ಫೋಟೋಗಳನ್ನು ಅಳಿಸುವುದೇ?", "यह जगह, इसके नाम और फ़ोटो हटाएँ?"),
 "placeDeleted": ("This place was deleted.", "ಈ ಸ್ಥಳವನ್ನು ಅಳಿಸಲಾಗಿದೆ.", "यह जगह हटा दी गई।"),
 "placeNeedsSomething": ("Enter a door no., building, name or landmark.", "ಮನೆ ಸಂಖ್ಯೆ, ಕಟ್ಟಡ, ಹೆಸರು ಅಥವಾ ಗುರುತು ನಮೂದಿಸಿ.", "मकान नं., इमारत, नाम या निशानी डालें।"),
 "doorNo": ("Door no.", "ಮನೆ ಸಂಖ್ಯೆ", "मकान नं."),
 "pickStreet": ("Choose street", "ರಸ್ತೆ ಆಯ್ಕೆಮಾಡಿ", "गली चुनें"),
 "searchStreet": ("Search street", "ರಸ್ತೆ ಹುಡುಕಿ", "गली खोजें"),
 "newStreet": ("New street", "ಹೊಸ ರಸ್ತೆ", "नई गली"),
 "newStreetNamed": ("New street “{name}”", "ಹೊಸ ರಸ್ತೆ “{name}”", "नई गली “{name}”"),
 "addressees": ("Names at this place", "ಈ ಸ್ಥಳದ ಹೆಸರುಗಳು", "इस जगह के नाम"),
 "addressee": ("Addressee", "ವಿಳಾಸದಾರ", "पाने वाला"),
 "addName": ("Add name", "ಹೆಸರು ಸೇರಿಸಿ", "नाम जोड़ें"),
 "name": ("Name", "ಹೆಸರು", "नाम"),
 "aliases": ("Other spellings / names", "ಇತರ ಬರವಣಿಗೆ / ಹೆಸರುಗಳು", "दूसरी वर्तनी / नाम"),
 "aliasesHelp": ("Separate with commas", "ಅಲ್ಪವಿರಾಮದಿಂದ ಬೇರ್ಪಡಿಸಿ", "कॉमा से अलग करें"),
 "phoneOptional": ("Phone (optional)", "ಫೋನ್ (ಐಚ್ಛಿಕ)", "फ़ोन (वैकल्पिक)"),
 "noteFlat": ("Note (flat, floor…)", "ಟಿಪ್ಪಣಿ (ಫ್ಲ್ಯಾಟ್, ಮಹಡಿ…)", "नोट (फ़्लैट, मंज़िल…)"),
 "landmark": ("Landmark", "ಗುರುತು", "निशानी"),
 "building": ("Building", "ಕಟ್ಟಡ", "इमारत"),
 "floorFlat": ("Floor / flat", "ಮಹಡಿ / ಫ್ಲ್ಯಾಟ್", "मंज़िल / फ़्लैट"),
 "notesHint": ("Notes: dog, gate, floor, timing", "ಟಿಪ್ಪಣಿ: ನಾಯಿ, ಗೇಟ್, ಮಹಡಿ, ಸಮಯ", "नोट: कुत्ता, गेट, मंज़िल, समय"),
 "quickDog": ("Dog", "ನಾಯಿ", "कुत्ता"),
 "quickGate": ("Gate locked", "ಗೇಟ್ ಬೀಗ", "गेट बंद"),
 "quickUpstairs": ("Upstairs", "ಮೇಲಿನ ಮಹಡಿ", "ऊपर"),
 "quickMorning": ("Morning only", "ಬೆಳಿಗ್ಗೆ ಮಾತ್ರ", "केवल सुबह"),
 "quickEvening": ("Evening only", "ಸಂಜೆ ಮಾತ್ರ", "केवल शाम"),
 "deliveryPref": ("Delivery preference", "ವಿತರಣೆ ಆದ್ಯತೆ", "डिलीवरी पसंद"),
 "prefSecurity": ("Leave with security", "ಸೆಕ್ಯುರಿಟಿಗೆ ಕೊಡಿ", "गार्ड को दें"),
 "prefNeighbour": ("Leave with neighbour", "ನೆರೆಯವರಿಗೆ ಕೊಡಿ", "पड़ोसी को दें"),
 "prefLetterBox": ("Letter box", "ಪತ್ರ ಪೆಟ್ಟಿಗೆ", "लेटर बॉक्स"),
 "prefShop": ("Shop below", "ಕೆಳಗಿನ ಅಂಗಡಿ", "नीचे की दुकान"),
 "pin": ("PIN code", "ಪಿನ್ ಕೋಡ್", "पिन कोड"),
 "placeHouse": ("House", "ಮನೆ", "घर"),
 "placeShop": ("Shop", "ಅಂಗಡಿ", "दुकान"),
 "placeOffice": ("Office", "ಕಚೇರಿ", "दफ़्तर"),
 "placeApartment": ("Apartment", "ಅಪಾರ್ಟ್‌ಮೆಂಟ್", "अपार्टमेंट"),
 "placeOther": ("Other", "ಇತರೆ", "अन्य"),
 "maxPhotos": ("Up to 3 photos per place", "ಪ್ರತಿ ಸ್ಥಳಕ್ಕೆ 3 ಫೋಟೋವರೆಗೆ", "हर जगह के लिए 3 फ़ोटो तक"),
 "photoCount": ("Photo {count}/3", "ಫೋಟೋ {count}/3", "फ़ोटो {count}/3"),
 "cameraError": ("Camera not available", "ಕ್ಯಾಮೆರಾ ಲಭ್ಯವಿಲ್ಲ", "कैमरा उपलब्ध नहीं"),
 "possibleDuplicates": ("Already saved close by — same place?", "ಹತ್ತಿರದಲ್ಲೇ ಈಗಾಗಲೇ ಉಳಿಸಲಾಗಿದೆ — ಅದೇ ಸ್ಥಳವೇ?", "पास में पहले से सहेजी गई — वही जगह?"),
 "openIt": ("Open", "ತೆರೆಯಿರಿ", "खोलें"),
 "gpsOff": ("Location is off. Turn it on.", "ಸ್ಥಳ (GPS) ಆಫ್ ಆಗಿದೆ. ಆನ್ ಮಾಡಿ.", "लोकेशन बंद है। चालू करें।"),
 "gpsDenied": ("Location permission is needed.", "ಸ್ಥಳದ ಅನುಮತಿ ಬೇಕು.", "लोकेशन की अनुमति चाहिए।"),
 "openSettings": ("Settings", "ಸೆಟ್ಟಿಂಗ್", "सेटिंग"),
 "gpsWaiting": ("Getting GPS…", "GPS ಪಡೆಯುತ್ತಿದೆ…", "GPS मिल रहा है…"),
 "gpsAccuracy": ("GPS accuracy {acc} m (want ≤ {want} m)", "GPS ನಿಖರತೆ {acc} ಮೀ (≤ {want} ಮೀ ಬೇಕು)", "GPS सटीकता {acc} मी (≤ {want} मी चाहिए)"),
 "gpsAccuracyShort": ("± {acc} m", "± {acc} ಮೀ", "± {acc} मी"),
 "gpsUseNow": ("Use this location", "ಈ ಸ್ಥಳ ಬಳಸಿ", "यही लोकेशन लें"),
 "gpsSaved": ("Location saved (± {acc} m)", "ಸ್ಥಳ ಉಳಿಸಲಾಗಿದೆ (± {acc} ಮೀ)", "लोकेशन सहेजी (± {acc} मी)"),
 "gpsRetake": ("Again", "ಮತ್ತೆ", "फिर से"),
 "gpsNotSet": ("No location saved", "ಸ್ಥಳ ಉಳಿಸಿಲ್ಲ", "लोकेशन नहीं सहेजी"),
 "gpsCapture": ("Get GPS", "GPS ಪಡೆಯಿರಿ", "GPS लें"),
 "updateGpsHere": ("Move pin to my current location", "ಪಿನ್ ಅನ್ನು ನನ್ನ ಈಗಿನ ಸ್ಥಳಕ್ಕೆ ಸರಿಸಿ", "पिन मेरी अभी की जगह पर लाएँ"),
 "updateGpsConfirm": ("Save your current location (± {acc} m) for this place?", "ನಿಮ್ಮ ಈಗಿನ ಸ್ಥಳವನ್ನು (± {acc} ಮೀ) ಈ ಸ್ಥಳಕ್ಕೆ ಉಳಿಸುವುದೇ?", "अपनी अभी की लोकेशन (± {acc} मी) इस जगह के लिए सहेजें?"),
 "mergeDuplicate": ("Merge a duplicate", "ನಕಲು ವಿಲೀನಗೊಳಿಸಿ", "डुप्लिकेट मिलाएँ"),
 "pickDuplicate": ("Pick the duplicate", "ನಕಲನ್ನು ಆಯ್ಕೆಮಾಡಿ", "डुप्लिकेट चुनें"),
 "mergeIntoThis": ("Merge into this place", "ಈ ಸ್ಥಳಕ್ಕೆ ವಿಲೀನಗೊಳಿಸಿ", "इस जगह में मिलाएँ"),
 "mergeConfirm": ("Names, photos and articles of the duplicate move here, then it is deleted.", "ನಕಲಿನ ಹೆಸರು, ಫೋಟೋ ಮತ್ತು ಟಪಾಲುಗಳು ಇಲ್ಲಿಗೆ ಬರುತ್ತವೆ, ನಂತರ ಅದು ಅಳಿಯುತ್ತದೆ.", "डुप्लिकेट के नाम, फ़ोटो और डाक यहाँ आ जाएँगे, फिर वह हट जाएगी।"),
 "merged": ("Merged", "ವಿಲೀನಗೊಂಡಿದೆ", "मिला दिया"),
 "navigate": ("Navigate", "ದಾರಿ ತೋರಿಸಿ", "रास्ता दिखाएँ"),
 "googleMaps": ("Google Maps", "ಗೂಗಲ್ ಮ್ಯಾಪ್ಸ್", "गूगल मैप्स"),
 "call": ("Call", "ಕರೆ", "कॉल"),
 "distanceAway": ("{distance} away", "{distance} ದೂರ", "{distance} दूर"),
 "searchTips": ("Type or speak a name, door no. (12/3), street, landmark or PIN. Kannada, Hindi and English spellings all work.", "ಹೆಸರು, ಮನೆ ಸಂಖ್ಯೆ (12/3), ರಸ್ತೆ, ಗುರುತು ಅಥವಾ PIN ಟೈಪ್ ಮಾಡಿ ಇಲ್ಲವೇ ಹೇಳಿ. ಕನ್ನಡ, ಹಿಂದಿ, ಇಂಗ್ಲಿಷ್ ಎಲ್ಲವೂ ಸರಿ.", "नाम, मकान नं. (12/3), गली, निशानी या PIN लिखें या बोलें। कन्नड़, हिंदी, अंग्रेज़ी सब चलेगा।"),
 "noResults": ("Nothing found. Try fewer letters or the door no.", "ಏನೂ ಸಿಗಲಿಲ್ಲ. ಕಡಿಮೆ ಅಕ್ಷರ ಅಥವಾ ಮನೆ ಸಂಖ್ಯೆ ಪ್ರಯತ್ನಿಸಿ.", "कुछ नहीं मिला। कम अक्षर या मकान नं. आज़माएँ।"),
 "allBeats": ("All beats", "ಎಲ್ಲಾ ಬೀಟ್", "सभी बीट"),
 "placeHasNoGps": ("This place has no GPS location yet. Edit it at the door to add one.", "ಈ ಸ್ಥಳಕ್ಕೆ ಇನ್ನೂ GPS ಇಲ್ಲ. ಮನೆ ಬಳಿ ತಿದ್ದಿ ಸೇರಿಸಿ.", "इस जगह की GPS लोकेशन नहीं है। दरवाज़े पर बदलकर जोड़ें।"),
 "arrived": ("You are here", "ನೀವು ತಲುಪಿದ್ದೀರಿ", "आप पहुँच गए"),
 "noCompass": ("No compass: arrow shows direction when walking.", "ದಿಕ್ಸೂಚಿ ಇಲ್ಲ: ನಡೆಯುವಾಗ ಬಾಣ ದಿಕ್ಕು ತೋರಿಸುತ್ತದೆ.", "कम्पास नहीं: चलते समय तीर दिशा दिखाएगा।"),
 "noNearby": ("No saved places near you.", "ನಿಮ್ಮ ಹತ್ತಿರ ಉಳಿಸಿದ ಸ್ಥಳಗಳಿಲ್ಲ.", "आपके पास कोई सहेजी जगह नहीं।"),
 "scanBarcode": ("Scan barcode", "ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನ್", "बारकोड स्कैन"),
 "scanAddress": ("Scan address", "ವಿಳಾಸ ಸ್ಕ್ಯಾನ್", "पता स्कैन"),
 "typeIn": ("Type", "ಟೈಪ್ ಮಾಡಿ", "टाइप करें"),
 "torch": ("Torch", "ಟಾರ್ಚ್", "टॉर्च"),
 "scannedCount": ("Scanned: {count}", "ಸ್ಕ್ಯಾನ್ ಆಗಿದೆ: {count}", "स्कैन हुए: {count}"),
 "addedCount": ("Added {count} articles", "{count} ಟಪಾಲು ಸೇರಿಸಲಾಗಿದೆ", "{count} डाक जोड़ी गईं"),
 "articleValid": ("Valid article number", "ಸರಿಯಾದ ಟಪಾಲು ಸಂಖ್ಯೆ", "सही आर्टिकल नंबर"),
 "articleBadCheck": ("Check digit does not match — please check the number", "ಪರಿಶೀಲನಾ ಅಂಕಿ ಹೊಂದುತ್ತಿಲ್ಲ — ಸಂಖ್ಯೆ ಪರಿಶೀಲಿಸಿ", "चेक अंक मेल नहीं खाता — नंबर जाँचें"),
 "articleOtherFormat": ("Other format (allowed)", "ಬೇರೆ ಮಾದರಿ (ಅನುಮತಿಸಲಾಗಿದೆ)", "दूसरा फ़ॉर्मेट (चलेगा)"),
 "articleInvalid": ("Too short / not valid", "ತುಂಬಾ ಚಿಕ್ಕದು / ಸರಿಯಲ್ಲ", "बहुत छोटा / सही नहीं"),
 "articleNo": ("Article number", "ಟಪಾಲು ಸಂಖ್ಯೆ", "आर्टिकल नंबर"),
 "articleNoOptional": ("Optional for ordinary letters", "ಸಾಮಾನ್ಯ ಪತ್ರಗಳಿಗೆ ಐಚ್ಛಿಕ", "साधारण पत्रों के लिए वैकल्पिक"),
 "addArticle": ("Add article", "ಟಪಾಲು ಸೇರಿಸಿ", "डाक जोड़ें"),
 "editArticle": ("Article", "ಟಪಾಲು", "डाक"),
 "deleteArticle": ("Delete article", "ಟಪಾಲು ಅಳಿಸಿ", "डाक हटाएँ"),
 "deleteArticleConfirm": ("Delete this article from today's list?", "ಈ ಟಪಾಲನ್ನು ಇಂದಿನ ಪಟ್ಟಿಯಿಂದ ಅಳಿಸುವುದೇ?", "यह डाक आज की सूची से हटाएँ?"),
 "duplicateArticle": ("Already added", "ಈಗಾಗಲೇ ಸೇರಿಸಲಾಗಿದೆ", "पहले से जोड़ी गई"),
 "duplicateArticleBody": ("{number} is already in today's list. Add again?", "{number} ಈಗಾಗಲೇ ಇಂದಿನ ಪಟ್ಟಿಯಲ್ಲಿದೆ. ಮತ್ತೆ ಸೇರಿಸುವುದೇ?", "{number} पहले से आज की सूची में है। फिर जोड़ें?"),
 "typeLetter": ("Letter", "ಪತ್ರ", "पत्र"),
 "typeRegistered": ("Registered", "ರಿಜಿಸ್ಟರ್ಡ್", "रजिस्टर्ड"),
 "typeSpeedPost": ("Speed Post", "ಸ್ಪೀಡ್ ಪೋಸ್ಟ್", "स्पीड पोस्ट"),
 "typeParcel": ("Parcel", "ಪಾರ್ಸೆಲ್", "पार्सल"),
 "typeMoneyOrder": ("Money order", "ಮನಿ ಆರ್ಡರ್", "मनी ऑर्डर"),
 "typeOther": ("Other", "ಇತರೆ", "अन्य"),
 "type": ("Type", "ಬಗೆ", "प्रकार"),
 "needsSignature": ("Needs signature / OTP", "ಸಹಿ / OTP ಬೇಕು", "हस्ताक्षर / OTP चाहिए"),
 "addressText": ("Address (as written)", "ವಿಳಾಸ (ಬರೆದಂತೆ)", "पता (जैसा लिखा है)"),
 "findMatch": ("Find match", "ಹೊಂದಿಕೆ ಹುಡುಕಿ", "मिलान खोजें"),
 "place": ("Place", "ಸ್ಥಳ", "जगह"),
 "suggestions": ("Suggestions — tap the right one", "ಸಲಹೆಗಳು — ಸರಿಯಾದುದನ್ನು ಒತ್ತಿ", "सुझाव — सही वाले पर दबाएँ"),
 "thisOne": ("This one", "ಇದೇ", "यही"),
 "noMatchFound": ("No saved place matches. Search or add a new place.", "ಉಳಿಸಿದ ಯಾವ ಸ್ಥಳವೂ ಹೊಂದುತ್ತಿಲ್ಲ. ಹುಡುಕಿ ಅಥವಾ ಹೊಸ ಸ್ಥಳ ಸೇರಿಸಿ.", "कोई सहेजी जगह मेल नहीं खाती। खोजें या नई जगह जोड़ें।"),
 "searchPlace": ("Search place", "ಸ್ಥಳ ಹುಡುಕಿ", "जगह खोजें"),
 "addNewPlace": ("Add new place", "ಹೊಸ ಸ್ಥಳ ಸೇರಿಸಿ", "नई जगह जोड़ें"),
 "pickPlace": ("Pick the place", "ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ", "जगह चुनें"),
 "unlink": ("Unlink", "ಸಂಪರ್ಕ ತೆಗೆಯಿರಿ", "जोड़ हटाएँ"),
 "ocrFailed": ("Could not read the text", "ಪಠ್ಯ ಓದಲಾಗಲಿಲ್ಲ", "लिखावट पढ़ी नहीं जा सकी"),
 "ocrNothing": ("No text found. Hold the camera closer, in good light.", "ಪಠ್ಯ ಸಿಗಲಿಲ್ಲ. ಉತ್ತಮ ಬೆಳಕಿನಲ್ಲಿ ಹತ್ತಿರ ಹಿಡಿಯಿರಿ.", "कोई लिखावट नहीं मिली। अच्छी रोशनी में पास से पकड़ें।"),
 "carryPrompt": ("{count} re-attempts from the last day", "ಹಿಂದಿನ ದಿನದ {count} ಮರುಪ್ರಯತ್ನಗಳು", "पिछले दिन के {count} दोबारा प्रयास"),
 "carriedCount": ("{count} re-attempts added", "{count} ಮರುಪ್ರಯತ್ನ ಸೇರಿಸಲಾಗಿದೆ", "{count} दोबारा प्रयास जोड़े गए"),
 "todayCounts": ("{total} articles · {pending} pending · {unmatched} unmatched", "{total} ಟಪಾಲು · {pending} ಬಾಕಿ · {unmatched} ಹೊಂದಿಲ್ಲ", "{total} डाक · {pending} बाकी · {unmatched} बिना जगह"),
 "noArticlesToday": ("No articles yet. Scan barcodes or addresses, or type them in.", "ಇನ್ನೂ ಟಪಾಲುಗಳಿಲ್ಲ. ಬಾರ್‌ಕೋಡ್ ಅಥವಾ ವಿಳಾಸ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ, ಇಲ್ಲವೇ ಟೈಪ್ ಮಾಡಿ.", "अभी कोई डाक नहीं। बारकोड या पता स्कैन करें, या टाइप करें।"),
 "unmatched": ("Unmatched — link to a place", "ಹೊಂದಿಲ್ಲ — ಸ್ಥಳಕ್ಕೆ ಜೋಡಿಸಿ", "बिना जगह — जगह से जोड़ें"),
 "matched": ("Matched", "ಹೊಂದಿದೆ", "जुड़ी हुई"),
 "planRoute": ("Plan route", "ಮಾರ್ಗ ಯೋಜಿಸಿ", "रास्ता बनाएँ"),
 "reattempt": ("Re-attempt", "ಮರುಪ್ರಯತ್ನ", "दोबारा प्रयास"),
 "statusPending": ("Pending", "ಬಾಕಿ", "बाकी"),
 "statusDelivered": ("Delivered", "ತಲುಪಿಸಲಾಗಿದೆ", "बाँटी गई"),
 "statusNotDelivered": ("Not delivered", "ತಲುಪಿಸಿಲ್ಲ", "नहीं बँटी"),
 "routePlan": ("Route plan", "ಮಾರ್ಗ ಯೋಜನೆ", "रास्ते की योजना"),
 "modeShortest": ("Shortest", "ಕಡಿಮೆ ದೂರ", "सबसे छोटा"),
 "modeStreet": ("Street order", "ರಸ್ತೆ ಕ್ರಮ", "गली क्रम"),
 "routeSummary": ("{stops} stops · about {distance}", "{stops} ನಿಲ್ದಾಣಗಳು · ಸುಮಾರು {distance}", "{stops} पड़ाव · लगभग {distance}"),
 "startFrom": ("Start: {where}", "ಆರಂಭ: {where}", "शुरुआत: {where}"),
 "startUnknown": ("Start point unknown (no GPS)", "ಆರಂಭ ಸ್ಥಳ ತಿಳಿದಿಲ್ಲ (GPS ಇಲ್ಲ)", "शुरुआत की जगह पता नहीं (GPS नहीं)"),
 "startOffice": ("Post office", "ಅಂಚೆ ಕಚೇರಿ", "डाकघर"),
 "startCurrent": ("My current location", "ನನ್ನ ಈಗಿನ ಸ್ಥಳ", "मेरी अभी की जगह"),
 "unmatchedNotInRoute": ("{count} unmatched articles are not in the route", "{count} ಹೊಂದದ ಟಪಾಲುಗಳು ಮಾರ್ಗದಲ್ಲಿಲ್ಲ", "{count} बिना जगह की डाक रास्ते में नहीं हैं"),
 "replan": ("Plan again", "ಮತ್ತೆ ಯೋಜಿಸಿ", "फिर से बनाएँ"),
 "allUnmatched": ("{count} articles are not linked to places yet. Link them in Today's articles.", "{count} ಟಪಾಲುಗಳು ಇನ್ನೂ ಸ್ಥಳಕ್ಕೆ ಜೋಡಣೆಯಾಗಿಲ್ಲ. ಇಂದಿನ ಟಪಾಲುಗಳಲ್ಲಿ ಜೋಡಿಸಿ.", "{count} डाक अभी जगहों से नहीं जुड़ी। आज की डाक में जोड़ें।"),
 "nothingToDeliver": ("Nothing pending to deliver today.", "ಇಂದು ತಲುಪಿಸಲು ಏನೂ ಬಾಕಿ ಇಲ್ಲ.", "आज बाँटने के लिए कुछ बाकी नहीं।"),
 "articlesCount": ("{count} articles", "{count} ಟಪಾಲು", "{count} डाक"),
 "noGps": ("no GPS", "GPS ಇಲ್ಲ", "GPS नहीं"),
 "startRun": ("Start delivery", "ವಿತರಣೆ ಆರಂಭಿಸಿ", "वितरण शुरू करें"),
 "run": ("Delivery", "ವಿತರಣೆ", "वितरण"),
 "stopsDone": ("{done} of {total} stops", "{total} ರಲ್ಲಿ {done} ನಿಲ್ದಾಣ", "{total} में से {done} पड़ाव"),
 "nextStop": ("NEXT STOP", "ಮುಂದಿನ ನಿಲ್ದಾಣ", "अगला पड़ाव"),
 "delivered": ("Delivered", "ತಲುಪಿಸಲಾಗಿದೆ", "बाँट दी"),
 "notDelivered": ("Not delivered", "ತಲುಪಿಸಲಾಗಿಲ್ಲ", "नहीं बँटी"),
 "skip": ("Skip", "ಬಿಟ್ಟುಬಿಡಿ", "छोड़ें"),
 "whyNotDelivered": ("Why not delivered?", "ಏಕೆ ತಲುಪಿಸಲಾಗಿಲ್ಲ?", "क्यों नहीं बँटी?"),
 "reasonDoorLocked": ("Door locked", "ಬಾಗಿಲು ಬೀಗ", "दरवाज़ा बंद"),
 "reasonAbsent": ("Addressee not available", "ವಿಳಾಸದಾರ ಇಲ್ಲ", "पाने वाला नहीं मिला"),
 "reasonLeft": ("Left / shifted", "ಬಿಟ್ಟು ಹೋಗಿದ್ದಾರೆ / ಸ್ಥಳಾಂತರ", "छोड़ गए / शिफ़्ट"),
 "reasonRefused": ("Refused", "ನಿರಾಕರಿಸಿದರು", "लेने से मना"),
 "reasonWrongAddress": ("Wrong / insufficient address", "ತಪ್ಪು / ಅಪೂರ್ಣ ವಿಳಾಸ", "गलत / अधूरा पता"),
 "reasonUnclaimed": ("Unclaimed", "ಯಾರೂ ಪಡೆಯಲಿಲ್ಲ", "किसी ने नहीं लिया"),
 "reasonOther": ("Other", "ಇತರೆ", "अन्य"),
 "runFinished": ("All stops done. Well done!", "ಎಲ್ಲಾ ನಿಲ್ದಾಣ ಮುಗಿಯಿತು. ಶಭಾಷ್!", "सारे पड़ाव पूरे। शाबाश!"),
 "ttsNext": ("Next: number {where}", "ಮುಂದಿನದು: ಸಂಖ್ಯೆ {where}", "अगला: नंबर {where}"),
 "history": ("History", "ಇತಿಹಾಸ", "इतिहास"),
 "noArticlesThatDay": ("No articles on this day.", "ಈ ದಿನ ಯಾವುದೇ ಟಪಾಲು ಇಲ್ಲ.", "इस दिन कोई डाक नहीं।"),
 "notDeliveredList": ("Not delivered", "ತಲುಪಿಸದವು", "जो नहीं बँटी"),
 "carryToTomorrow": ("Carry {count} re-attempts to next day", "{count} ಮರುಪ್ರಯತ್ನಗಳನ್ನು ಮರುದಿನಕ್ಕೆ ಸೇರಿಸಿ", "{count} दोबारा प्रयास अगले दिन में जोड़ें"),
 "summaryTotals": ("Total {total}: delivered {delivered}, not delivered {notDelivered}, pending {pending}", "ಒಟ್ಟು {total}: ತಲುಪಿಸಿದ್ದು {delivered}, ತಲುಪಿಸದ್ದು {notDelivered}, ಬಾಕಿ {pending}", "कुल {total}: बँटी {delivered}, नहीं बँटी {notDelivered}, बाकी {pending}"),
 "summaryTypeLine": ("{type}: {delivered}/{total} delivered", "{type}: {delivered}/{total} ತಲುಪಿಸಲಾಗಿದೆ", "{type}: {delivered}/{total} बँटी"),
 "distanceLine": ("Planned route {planned} · recorded {recorded}", "ಯೋಜಿತ ಮಾರ್ಗ {planned} · ದಾಖಲಾದದ್ದು {recorded}", "योजना का रास्ता {planned} · दर्ज {recorded}"),
 "learnedPercent": ("{percent}% of places learned", "{percent}% ಸ್ಥಳಗಳು ಕಲಿತಿದ್ದೀರಿ", "{percent}% जगहें सीख लीं"),
 "learnedOf": ("{learned} of {total} places", "{total} ರಲ್ಲಿ {learned} ಸ್ಥಳಗಳು", "{total} में से {learned} जगहें"),
 "weakStreets": ("Streets to practise", "ಅಭ್ಯಾಸ ಬೇಕಾದ ರಸ್ತೆಗಳು", "अभ्यास वाली गलियाँ"),
 "quizPhoto": ("Photo → place", "ಫೋಟೋ → ಸ್ಥಳ", "फ़ोटो → जगह"),
 "quizPhotoSub": ("See the house photo, pick the door no. and street", "ಮನೆಯ ಫೋಟೋ ನೋಡಿ, ಮನೆ ಸಂಖ್ಯೆ ಮತ್ತು ರಸ್ತೆ ಆರಿಸಿ", "घर की फ़ोटो देखें, मकान नं. और गली चुनें"),
 "quizName": ("Name → door no.", "ಹೆಸರು → ಮನೆ ಸಂಖ್ಯೆ", "नाम → मकान नं."),
 "quizNameSub": ("Where does this person live?", "ಈ ವ್ಯಕ್ತಿ ಎಲ್ಲಿ ವಾಸಿಸುತ್ತಾರೆ?", "यह व्यक्ति कहाँ रहता है?"),
 "quizDoor": ("Door no. → landmark", "ಮನೆ ಸಂಖ್ಯೆ → ಗುರುತು", "मकान नं. → निशानी"),
 "quizDoorSub": ("What landmark is near this door?", "ಈ ಮನೆಯ ಹತ್ತಿರ ಯಾವ ಗುರುತು?", "इस दरवाज़े के पास कौन-सी निशानी है?"),
 "walkMode": ("Walk mode", "ನಡಿಗೆ ಮೋಡ್", "चलते-चलते"),
 "walkModeSub": ("Walk the beat; the app quizzes you about the nearest house", "ಬೀಟ್‌ನಲ್ಲಿ ನಡೆಯಿರಿ; ಹತ್ತಿರದ ಮನೆಯ ಬಗ್ಗೆ ಆ್ಯಪ್ ಪ್ರಶ್ನೆ ಕೇಳುತ್ತದೆ", "बीट पर चलें; ऐप सबसे पास के घर के बारे में पूछेगा"),
 "resetProgress": ("Reset learning progress", "ಕಲಿಕೆ ಪ್ರಗತಿ ಮರುಹೊಂದಿಸಿ", "सीखने की प्रगति रीसेट करें"),
 "resetProgressConfirm": ("Start learning this beat from zero?", "ಈ ಬೀಟ್ ಕಲಿಕೆಯನ್ನು ಸೊನ್ನೆಯಿಂದ ಆರಂಭಿಸುವುದೇ?", "इस बीट को शून्य से सीखना शुरू करें?"),
 "qWhichPlace": ("Which place is this?", "ಇದು ಯಾವ ಸ್ಥಳ?", "यह कौन-सी जगह है?"),
 "qWhereLives": ("Where does {name} get mail?", "{name} ಅವರ ಟಪಾಲು ಎಲ್ಲಿಗೆ?", "{name} की डाक कहाँ जाती है?"),
 "qLandmarkOf": ("Landmark near {place}?", "{place} ಹತ್ತಿರದ ಗುರುತು?", "{place} के पास की निशानी?"),
 "qWhoLivesHere": ("Who gets mail here?", "ಇಲ್ಲಿ ಯಾರಿಗೆ ಟಪಾಲು ಬರುತ್ತದೆ?", "यहाँ किसकी डाक आती है?"),
 "correct": ("Correct!", "ಸರಿ!", "सही!"),
 "wrongAnswer": ("Answer: {answer}", "ಉತ್ತರ: {answer}", "उत्तर: {answer}"),
 "scoreLine": ("Score {right}/{total}", "ಅಂಕ {right}/{total}", "स्कोर {right}/{total}"),
 "notEnoughForQuiz": ("Add more places (with photos, names, landmarks) to practise.", "ಅಭ್ಯಾಸಕ್ಕೆ ಹೆಚ್ಚು ಸ್ಥಳಗಳನ್ನು (ಫೋಟೋ, ಹೆಸರು, ಗುರುತು ಸಹಿತ) ಸೇರಿಸಿ.", "अभ्यास के लिए और जगहें (फ़ोटो, नाम, निशानी के साथ) जोड़ें।"),
 "nearestPlace": ("Nearest saved place · {distance}", "ಹತ್ತಿರದ ಉಳಿಸಿದ ಸ್ಥಳ · {distance}", "सबसे पास की सहेजी जगह · {distance}"),
 "walkHint": ("Walk closer (within 40 m) to a house you have not answered yet.", "ಇನ್ನೂ ಉತ್ತರಿಸದ ಮನೆಗೆ ಹತ್ತಿರ (40 ಮೀ ಒಳಗೆ) ನಡೆಯಿರಿ.", "जिस घर का जवाब नहीं दिया, उसके पास (40 मी के भीतर) जाएँ।"),
 "handover": ("Handover to a relief postman", "ರಿಲೀಫ್ ಅಂಚೆಯಣ್ಣರಿಗೆ ಹಸ್ತಾಂತರ", "रिलीफ़ डाकिये को सौंपें"),
 "handoverHelp": ("Export a beat as a password-protected encrypted file and share it. Tell the password separately (by phone, not in the same message).", "ಬೀಟ್ ಅನ್ನು ಪಾಸ್‌ವರ್ಡ್ ರಕ್ಷಿತ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಫೈಲ್ ಆಗಿ ಕಳುಹಿಸಿ. ಪಾಸ್‌ವರ್ಡ್ ಅನ್ನು ಬೇರೆಯಾಗಿ (ಫೋನ್‌ನಲ್ಲಿ) ತಿಳಿಸಿ.", "बीट को पासवर्ड-सुरक्षित एन्क्रिप्टेड फ़ाइल बनाकर भेजें। पासवर्ड अलग से (फ़ोन पर) बताएँ।"),
 "handoverExport": ("Export beat", "ಬೀಟ್ ರಫ್ತು", "बीट निर्यात करें"),
 "handoverShareText": ("Beat Mitra beat file. Open it in Beat Mitra → Handover & backup → Import.", "ಬೀಟ್ ಮಿತ್ರ ಬೀಟ್ ಫೈಲ್. ಬೀಟ್ ಮಿತ್ರ → ಹಸ್ತಾಂತರ ಮತ್ತು ಬ್ಯಾಕಪ್ → ಆಮದು ಮೂಲಕ ತೆರೆಯಿರಿ.", "बीट मित्र बीट फ़ाइल। बीट मित्र → सौंपना और बैकअप → आयात में खोलें।"),
 "chooseBeats": ("Beats to include", "ಸೇರಿಸಬೇಕಾದ ಬೀಟ್‌ಗಳು", "शामिल बीट"),
 "includePhones": ("Include phone numbers", "ಫೋನ್ ಸಂಖ್ಯೆಗಳನ್ನು ಸೇರಿಸಿ", "फ़ोन नंबर शामिल करें"),
 "createAndShare": ("Create & share", "ರಚಿಸಿ ಹಂಚಿ", "बनाएँ और भेजें"),
 "password": ("Password", "ಪಾಸ್‌ವರ್ಡ್", "पासवर्ड"),
 "passwordAgain": ("Password again", "ಪಾಸ್‌ವರ್ಡ್ ಮತ್ತೊಮ್ಮೆ", "पासवर्ड दोबारा"),
 "passwordHelp": ("At least 6 characters. Without it the file cannot be opened.", "ಕನಿಷ್ಠ 6 ಅಕ್ಷರ. ಇದಿಲ್ಲದೆ ಫೈಲ್ ತೆರೆಯಲಾಗದು.", "कम से कम 6 अक्षर। इसके बिना फ़ाइल नहीं खुलेगी।"),
 "passwordTooShort": ("Password must be at least 6 characters", "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರ ಇರಬೇಕು", "पासवर्ड कम से कम 6 अक्षर का हो"),
 "passwordMismatch": ("Passwords do not match", "ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಹೊಂದುತ್ತಿಲ್ಲ", "पासवर्ड मेल नहीं खाते"),
 "importBeat": ("Import a beat file", "ಬೀಟ್ ಫೈಲ್ ಆಮದು", "बीट फ़ाइल आयात करें"),
 "enterFilePassword": ("Password of the file", "ಫೈಲ್‌ನ ಪಾಸ್‌ವರ್ಡ್", "फ़ाइल का पासवर्ड"),
 "wrongPassword": ("Wrong password", "ತಪ್ಪು ಪಾಸ್‌ವರ್ಡ್", "गलत पासवर्ड"),
 "notBeatMitraFile": ("This is not a Beat Mitra file", "ಇದು ಬೀಟ್ ಮಿತ್ರ ಫೈಲ್ ಅಲ್ಲ", "यह बीट मित्र फ़ाइल नहीं है"),
 "importDone": ("Imported {beats} beats, {places} places, {photos} photos", "{beats} ಬೀಟ್, {places} ಸ್ಥಳ, {photos} ಫೋಟೋ ಆಮದಾಗಿದೆ", "{beats} बीट, {places} जगहें, {photos} फ़ोटो आयात हुए"),
 "thisIsHandover": ("This is a beat file: its beats are added to yours.", "ಇದು ಬೀಟ್ ಫೈಲ್: ಅದರ ಬೀಟ್‌ಗಳು ನಿಮ್ಮವುಗಳಿಗೆ ಸೇರುತ್ತವೆ.", "यह बीट फ़ाइल है: इसकी बीट आपकी बीट में जुड़ेंगी।"),
 "fullBackup": ("Full backup", "ಪೂರ್ಣ ಬ್ಯಾಕಪ್", "पूरा बैकअप"),
 "fullBackupHelp": ("Everything (beats, places, photos, history) in one encrypted file. Save it to a pen drive, SD card or computer.", "ಎಲ್ಲವೂ (ಬೀಟ್, ಸ್ಥಳ, ಫೋಟೋ, ಇತಿಹಾಸ) ಒಂದೇ ಎನ್‌ಕ್ರಿಪ್ಟ್ ಫೈಲ್‌ನಲ್ಲಿ. ಪೆನ್ ಡ್ರೈವ್, SD ಕಾರ್ಡ್ ಅಥವಾ ಕಂಪ್ಯೂಟರ್‌ಗೆ ಉಳಿಸಿ.", "सब कुछ (बीट, जगहें, फ़ोटो, इतिहास) एक एन्क्रिप्टेड फ़ाइल में। पेन ड्राइव, SD कार्ड या कंप्यूटर में रखें।"),
 "backupAdvice": ("Data lives only on this phone. If the phone is lost, only a backup can bring it back.", "ಮಾಹಿತಿ ಈ ಫೋನಿನಲ್ಲಿ ಮಾತ್ರ ಇದೆ. ಫೋನ್ ಕಳೆದರೆ ಬ್ಯಾಕಪ್ ಮಾತ್ರ ಉಳಿಸುತ್ತದೆ.", "डेटा केवल इसी फ़ोन में है। फ़ोन खोने पर केवल बैकअप ही बचाएगा।"),
 "neverBackedUp": ("Never backed up", "ಎಂದೂ ಬ್ಯಾಕಪ್ ಮಾಡಿಲ್ಲ", "कभी बैकअप नहीं लिया"),
 "lastBackup": ("Last backup: {when}", "ಕೊನೆಯ ಬ್ಯಾಕಪ್: {when}", "पिछला बैकअप: {when}"),
 "backupNow": ("Back up now", "ಈಗ ಬ್ಯಾಕಪ್ ಮಾಡಿ", "अभी बैकअप लें"),
 "chooseLocation": ("Choose where to save", "ಎಲ್ಲಿ ಉಳಿಸಬೇಕು ಆರಿಸಿ", "कहाँ सहेजें चुनें"),
 "backupSaved": ("Backup saved", "ಬ್ಯಾಕಪ್ ಉಳಿಸಲಾಗಿದೆ", "बैकअप सहेजा गया"),
 "restoreBackup": ("Restore a backup", "ಬ್ಯಾಕಪ್ ಮರುಸ್ಥಾಪಿಸಿ", "बैकअप वापस लाएँ"),
 "restore": ("Restore", "ಮರುಸ್ಥಾಪಿಸಿ", "वापस लाएँ"),
 "restoreConfirm": ("All current data on this phone will be replaced by the backup. Continue?", "ಈ ಫೋನಿನ ಈಗಿನ ಎಲ್ಲಾ ಮಾಹಿತಿ ಬ್ಯಾಕಪ್‌ನಿಂದ ಬದಲಾಗುತ್ತದೆ. ಮುಂದುವರಿಸುವುದೇ?", "इस फ़ोन का सारा मौजूदा डेटा बैकअप से बदल जाएगा। जारी रखें?"),
 "display": ("Display", "ಪ್ರದರ್ಶನ", "डिस्प्ले"),
 "language": ("Language", "ಭಾಷೆ", "भाषा"),
 "deviceLanguage": ("Phone language", "ಫೋನಿನ ಭಾಷೆ", "फ़ोन की भाषा"),
 "theme": ("Theme", "ಥೀಮ್", "थीम"),
 "themeSystem": ("Same as phone", "ಫೋನಿನಂತೆ", "फ़ोन जैसा"),
 "themeLight": ("Light", "ಬೆಳಕು", "हल्का"),
 "themeDark": ("Dark", "ಕತ್ತಲು", "गहरा"),
 "sunlightMode": ("Sunlight mode", "ಬಿಸಿಲು ಮೋಡ್", "धूप मोड"),
 "sunlightModeSub": ("Extra contrast for bright sun", "ಬಿಸಿಲಿನಲ್ಲಿ ಹೆಚ್ಚು ಸ್ಪಷ್ಟತೆ", "तेज़ धूप के लिए ज़्यादा कंट्रास्ट"),
 "textSize": ("Text size", "ಅಕ್ಷರ ಗಾತ್ರ", "अक्षर का आकार"),
 "textNormal": ("Normal", "ಸಾಮಾನ್ಯ", "सामान्य"),
 "textLarge": ("Large", "ದೊಡ್ಡ", "बड़ा"),
 "textXL": ("Extra large", "ಅತಿ ದೊಡ್ಡ", "बहुत बड़ा"),
 "security": ("Security", "ಭದ್ರತೆ", "सुरक्षा"),
 "changePin": ("Change PIN", "PIN ಬದಲಿಸಿ", "PIN बदलें"),
 "autoLock": ("Auto-lock", "ಸ್ವಯಂ ಲಾಕ್", "अपने-आप लॉक"),
 "lockImmediately": ("Immediately", "ತಕ್ಷಣ", "तुरंत"),
 "lockAfterMin": ("After {minutes} min", "{minutes} ನಿಮಿಷದ ನಂತರ", "{minutes} मिनट बाद"),
 "blockScreenshots": ("Block screenshots", "ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ತಡೆಯಿರಿ", "स्क्रीनशॉट रोकें"),
 "blockScreenshotsSub": ("Also hides the app in recent apps", "ಇತ್ತೀಚಿನ ಆ್ಯಪ್ ಪಟ್ಟಿಯಲ್ಲೂ ಮರೆಮಾಡುತ್ತದೆ", "हाल के ऐप में भी छिपाता है"),
 "gpsAndRoute": ("GPS & route", "GPS ಮತ್ತು ಮಾರ್ಗ", "GPS और रास्ता"),
 "gpsThreshold": ("GPS accuracy needed", "ಬೇಕಾದ GPS ನಿಖರತೆ", "ज़रूरी GPS सटीकता"),
 "startPoint": ("Route start point", "ಮಾರ್ಗದ ಆರಂಭ ಸ್ಥಳ", "रास्ते की शुरुआत"),
 "setOfficeHere": ("Post office = where I am now", "ಅಂಚೆ ಕಚೇರಿ = ನಾನು ಈಗ ಇರುವ ಸ್ಥಳ", "डाकघर = जहाँ मैं अभी हूँ"),
 "vibrateNear": ("Vibrate within 20 m of the place", "ಸ್ಥಳದ 20 ಮೀ ಒಳಗೆ ಕಂಪಿಸು", "जगह के 20 मी में कंपन"),
 "ttsSetting": ("Read out next stop", "ಮುಂದಿನ ನಿಲ್ದಾಣ ಓದಿ ಹೇಳು", "अगला पड़ाव बोलकर बताएँ"),
 "ttsSettingSub": ("Uses the phone's text-to-speech", "ಫೋನಿನ ಮಾತು ಸೌಲಭ್ಯ ಬಳಸುತ್ತದೆ", "फ़ोन की टेक्स्ट-टू-स्पीच से"),
 "dataSection": ("Data", "ಮಾಹಿತಿ", "डेटा"),
 "historyRetention": ("Keep delivery history", "ವಿತರಣೆ ಇತಿಹಾಸ ಇಡಿ", "वितरण इतिहास रखें"),
 "daysCount": ("{days} days", "{days} ದಿನ", "{days} दिन"),
 "oldDeleted": ("{count} old articles deleted", "{count} ಹಳೆಯ ಟಪಾಲು ಅಳಿಸಲಾಗಿದೆ", "{count} पुरानी डाक हटाई गई"),
 "onlineMap": ("Online map (OpenStreetMap)", "ಆನ್‌ಲೈನ್ ನಕ್ಷೆ (OpenStreetMap)", "ऑनलाइन नक्शा (OpenStreetMap)"),
 "onlineMapSub": ("Off by default. Needs internet only for map pictures.", "ಮೊದಲಿಗೆ ಆಫ್. ನಕ್ಷೆ ಚಿತ್ರಗಳಿಗೆ ಮಾತ್ರ ಇಂಟರ್ನೆಟ್.", "शुरू में बंद। केवल नक्शे की तस्वीरों के लिए इंटरनेट।"),
 "onlineMapConfirm": ("The map downloads map pictures from OpenStreetMap while you look at it. Your names and addresses are never sent. Turn on?", "ನೀವು ನೋಡುವಾಗ ನಕ್ಷೆ OpenStreetMap ನಿಂದ ಚಿತ್ರಗಳನ್ನು ತರುತ್ತದೆ. ನಿಮ್ಮ ಹೆಸರು, ವಿಳಾಸಗಳನ್ನು ಎಂದೂ ಕಳುಹಿಸುವುದಿಲ್ಲ. ಆನ್ ಮಾಡುವುದೇ?", "देखते समय नक्शा OpenStreetMap से तस्वीरें लाता है। आपके नाम और पते कभी नहीं भेजे जाते। चालू करें?"),
 "mapNotInBuild": ("This is the offline build (no internet permission). Install the “map” build to use the online map.", "ಇದು ಆಫ್‌ಲೈನ್ ಆವೃತ್ತಿ (ಇಂಟರ್ನೆಟ್ ಅನುಮತಿ ಇಲ್ಲ). ಆನ್‌ಲೈನ್ ನಕ್ಷೆಗೆ “map” ಆವೃತ್ತಿ ಹಾಕಿ.", "यह ऑफ़लाइन संस्करण है (इंटरनेट अनुमति नहीं)। ऑनलाइन नक्शे के लिए “map” संस्करण लगाएँ।"),
 "deleteAll": ("Delete all data", "ಎಲ್ಲಾ ಮಾಹಿತಿ ಅಳಿಸಿ", "सारा डेटा हटाएँ"),
 "deleteAllConfirm1": ("This deletes all beats, places, photos, names and history from this phone. It cannot be undone. Make a backup first.", "ಇದು ಈ ಫೋನಿನ ಎಲ್ಲಾ ಬೀಟ್, ಸ್ಥಳ, ಫೋಟೋ, ಹೆಸರು ಮತ್ತು ಇತಿಹಾಸ ಅಳಿಸುತ್ತದೆ. ಮರಳಿ ಪಡೆಯಲಾಗದು. ಮೊದಲು ಬ್ಯಾಕಪ್ ಮಾಡಿ.", "यह इस फ़ोन से सारी बीट, जगहें, फ़ोटो, नाम और इतिहास हटा देगा। वापस नहीं आएगा। पहले बैकअप लें।"),
 "deleteAllConfirm2": ("Type DELETE to confirm", "ಖಚಿತಪಡಿಸಲು DELETE ಎಂದು ಟೈಪ್ ಮಾಡಿ", "पुष्टि के लिए DELETE लिखें"),
 "notDeleted": ("Nothing was deleted", "ಏನೂ ಅಳಿಸಲಿಲ್ಲ", "कुछ नहीं हटाया गया"),
 "helpAndAbout": ("Help & about", "ಸಹಾಯ ಮತ್ತು ಮಾಹಿತಿ", "मदद और जानकारी"),
 "licences": ("Open-source licences", "ಮುಕ್ತ ಮೂಲ ಪರವಾನಗಿಗಳು", "ओपन-सोर्स लाइसेंस"),
 "help1Title": ("Create your beat and streets", "ನಿಮ್ಮ ಬೀಟ್ ಮತ್ತು ರಸ್ತೆಗಳನ್ನು ರಚಿಸಿ", "अपनी बीट और गलियाँ बनाएँ"),
 "help1Body": ("Add each street and drag them into the order you usually walk.", "ಪ್ರತಿ ರಸ್ತೆ ಸೇರಿಸಿ, ನೀವು ಸಾಮಾನ್ಯವಾಗಿ ನಡೆಯುವ ಕ್ರಮಕ್ಕೆ ಎಳೆದು ಜೋಡಿಸಿ.", "हर गली जोड़ें और उन्हें अपने रोज़ के चलने के क्रम में खींचकर लगाएँ।"),
 "help2Title": ("“Add here” at each door", "ಪ್ರತಿ ಮನೆಯ ಬಳಿ “ಇಲ್ಲಿ ಸೇರಿಸಿ”", "हर दरवाज़े पर “यहाँ जोड़ें”"),
 "help2Body": ("GPS is saved, take 1–3 photos, then the door no., street, names (speak them) and notes like “dog”.", "GPS ಉಳಿಯುತ್ತದೆ, 1–3 ಫೋಟೋ ತೆಗೆಯಿರಿ, ನಂತರ ಮನೆ ಸಂಖ್ಯೆ, ರಸ್ತೆ, ಹೆಸರು (ಹೇಳಿ) ಮತ್ತು “ನಾಯಿ” ಮುಂತಾದ ಟಿಪ್ಪಣಿ.", "GPS सहेजा जाता है, 1–3 फ़ोटो लें, फिर मकान नं., गली, नाम (बोलकर) और “कुत्ता” जैसे नोट।"),
 "help3Title": ("Search anything", "ಏನನ್ನಾದರೂ ಹುಡುಕಿ", "कुछ भी खोजें"),
 "help3Body": ("Type or speak a name, door no., street or landmark. Small spelling mistakes are fine.", "ಹೆಸರು, ಮನೆ ಸಂಖ್ಯೆ, ರಸ್ತೆ ಅಥವಾ ಗುರುತು ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಹೇಳಿ. ಸಣ್ಣ ತಪ್ಪುಗಳು ಸರಿ.", "नाम, मकान नं., गली या निशानी लिखें या बोलें। छोटी गलतियाँ चलेंगी।"),
 "help4Title": ("Follow the arrow", "ಬಾಣವನ್ನು ಅನುಸರಿಸಿ", "तीर के पीछे चलें"),
 "help4Body": ("Navigate shows a big arrow and metres to the house — no internet needed. The phone vibrates when you are close.", "ದಾರಿ ತೋರಿಸಿ — ದೊಡ್ಡ ಬಾಣ ಮತ್ತು ಮನೆಗೆ ಮೀಟರ್ ದೂರ; ಇಂಟರ್ನೆಟ್ ಬೇಡ. ಹತ್ತಿರ ಬಂದಾಗ ಫೋನ್ ಕಂಪಿಸುತ್ತದೆ.", "रास्ता दिखाएँ — बड़ा तीर और घर तक मीटर; इंटरनेट नहीं चाहिए। पास आने पर फ़ोन काँपता है।"),
 "help5Title": ("Add today's articles", "ಇಂದಿನ ಟಪಾಲು ಸೇರಿಸಿ", "आज की डाक जोड़ें"),
 "help5Body": ("Scan the barcode, or photograph the address — the app suggests the matching house. Confirm with one tap.", "ಬಾರ್‌ಕೋಡ್ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ ಅಥವಾ ವಿಳಾಸದ ಫೋಟೋ ತೆಗೆಯಿರಿ — ಆ್ಯಪ್ ಹೊಂದುವ ಮನೆ ಸೂಚಿಸುತ್ತದೆ. ಒಂದೇ ಒತ್ತಿನಲ್ಲಿ ಖಚಿತಪಡಿಸಿ.", "बारकोड स्कैन करें या पते की फ़ोटो लें — ऐप मिलता घर सुझाएगा। एक टैप में पक्का करें।"),
 "help6Title": ("Plan and deliver", "ಯೋಜಿಸಿ ಮತ್ತು ತಲುಪಿಸಿ", "योजना बनाएँ और बाँटें"),
 "help6Body": ("Plan the route, then press ✅ Delivered or ❌ Not delivered at each stop.", "ಮಾರ್ಗ ಯೋಜಿಸಿ, ನಂತರ ಪ್ರತಿ ನಿಲ್ದಾಣದಲ್ಲಿ ✅ ತಲುಪಿಸಲಾಗಿದೆ ಅಥವಾ ❌ ತಲುಪಿಸಲಾಗಿಲ್ಲ ಒತ್ತಿ.", "रास्ता बनाएँ, फिर हर पड़ाव पर ✅ बाँट दी या ❌ नहीं बँटी दबाएँ।"),
 "help7Title": ("Day summary", "ದಿನದ ಸಾರಾಂಶ", "दिन का सारांश"),
 "help7Body": ("See counts and reasons, carry re-attempts to the next day and share the summary text.", "ಎಣಿಕೆ ಮತ್ತು ಕಾರಣಗಳನ್ನು ನೋಡಿ, ಮರುಪ್ರಯತ್ನಗಳನ್ನು ಮರುದಿನಕ್ಕೆ ಸೇರಿಸಿ, ಸಾರಾಂಶ ಹಂಚಿಕೊಳ್ಳಿ.", "गिनती और कारण देखें, दोबारा प्रयास अगले दिन में जोड़ें और सारांश भेजें।"),
 "help8Title": ("Learn a new beat", "ಹೊಸ ಬೀಟ್ ಕಲಿಯಿರಿ", "नई बीट सीखें"),
 "help8Body": ("Practise with photo and name cards, or use walk mode while walking the beat.", "ಫೋಟೋ ಮತ್ತು ಹೆಸರಿನ ಕಾರ್ಡ್‌ಗಳಿಂದ ಅಭ್ಯಾಸ ಮಾಡಿ, ಅಥವಾ ನಡೆಯುವಾಗ ನಡಿಗೆ ಮೋಡ್ ಬಳಸಿ.", "फ़ोटो और नाम कार्ड से अभ्यास करें, या चलते समय चलते-चलते मोड लें।"),
 "help9Title": ("Handover and backup", "ಹಸ್ತಾಂತರ ಮತ್ತು ಬ್ಯಾಕಪ್", "सौंपना और बैकअप"),
 "help9Body": ("Give your beat to a relief postman as an encrypted file. Make a full backup every week.", "ನಿಮ್ಮ ಬೀಟ್ ಅನ್ನು ಎನ್‌ಕ್ರಿಪ್ಟ್ ಫೈಲ್ ಆಗಿ ರಿಲೀಫ್ ಅಂಚೆಯಣ್ಣರಿಗೆ ನೀಡಿ. ಪ್ರತಿ ವಾರ ಪೂರ್ಣ ಬ್ಯಾಕಪ್ ಮಾಡಿ.", "अपनी बीट रिलीफ़ डाकिये को एन्क्रिप्टेड फ़ाइल में दें। हर हफ़्ते पूरा बैकअप लें।"),
 "helpKannadaOcr": ("Note: the on-device text reader understands English and Hindi (Devanagari) print, but not Kannada script. For Kannada addresses, search by name or door no. — Kannada typing and voice search work.", "ಗಮನಿಸಿ: ಫೋನಿನ ಪಠ್ಯ ಓದುಗ ಇಂಗ್ಲಿಷ್ ಮತ್ತು ಹಿಂದಿ (ದೇವನಾಗರಿ) ಮುದ್ರಣ ಓದುತ್ತದೆ, ಕನ್ನಡ ಲಿಪಿ ಅಲ್ಲ. ಕನ್ನಡ ವಿಳಾಸಕ್ಕೆ ಹೆಸರು ಅಥವಾ ಮನೆ ಸಂಖ್ಯೆಯಿಂದ ಹುಡುಕಿ — ಕನ್ನಡ ಟೈಪಿಂಗ್ ಮತ್ತು ಧ್ವನಿ ಹುಡುಕಾಟ ಕೆಲಸ ಮಾಡುತ್ತದೆ.", "ध्यान दें: फ़ोन का टेक्स्ट रीडर अंग्रेज़ी और हिंदी (देवनागरी) छपाई पढ़ता है, कन्नड़ लिपि नहीं। कन्नड़ पतों के लिए नाम या मकान नं. से खोजें — कन्नड़ टाइपिंग और बोलकर खोज चलती है।"),
}

INT_PARAMS = {"count", "pending", "done", "acc", "want", "total", "unmatched", "stops", "delivered", "notDelivered",
              "percent", "learned", "right", "beats", "places", "photos", "days", "minutes"}
